#!/usr/bin/env python3
"""Build the Santiam Hospital & Clinics one-sheet social report.

Everything is emitted as STATIC HTML. Nothing on the page is generated by
client-side JavaScript, because the Artifact viewer does not execute page
scripts: any table body or chart built in JS renders as an empty shell there.
For the same reason the logo carries its fills as attributes rather than a
<style> block inside the SVG, which the viewer strips.

Output is ASCII-only. An Artifact is wrapped in a <head> we do not control, so
we cannot declare <meta charset>; numeric entities are encoding-independent.
"""
import pathlib

ROOT = pathlib.Path(__file__).parent
LOGO = (ROOT / 'assets' / 'logo-inline.svg').read_text().strip()

MONTHS = ["J", "F", "M", "A", "M", "J", "J", "A"]

# ---------------------------------------------------------------- data
# Still creative, organic medians per post, split by platform.
# Source: data/creative-by-platform.json
CREATIVE = [
    dict(name="Real photograph", desc="Staff, patients, events, facilities",
         fb=(24, "956", "14"), ig=(21, "288", "15"),
         strength="Wins on Instagram", hi="ig"),
    dict(name="Provider card", desc="Real headshot in a branded template",
         fb=(7, "1,933", "22"), ig=(6, "170", "5"),
         strength="Widest reach on FB", hi="fb"),
    dict(name="Designed graphic", desc="Dates, registration, awareness months",
         fb=(76, "547", "5.5"), ig=(54, "116", "3"),
         strength="Most shares on FB", hi=""),
]

VIDEO_ROW = dict(posts=25, reach="323", react="18", er="2.90%")

# Engagement rate by month. Source: data/computed.json
ER_MONTHLY = [
    ("Facebook", "Santiam Hospital &amp; Clinics", [0.42, 0.36, 0.26, 0.18, 0.19, 0.43, 0.39, 0.52]),
    ("Instagram", "santiamhospitalandclinics",     [0.81, 1.14, 0.90, 1.97, 1.51, 0.74, 0.80, 1.17]),
    ("Facebook", "Family Birth Center",            [6.35, 3.38, 2.69, 2.22, 3.41, 1.80, 2.94, 3.94]),
    ("LinkedIn", "Platform formula",               [8.10, 3.50, 2.30, 5.00, 4.60, 3.30, 3.90, 3.10]),
]

TOP_VIDEOS = [
    ("CEO message on Regence Blue Cross Blue Shield", "Jan 21 &middot; Facebook + Instagram", "12,330", "157", "10s"),
    ("Construction underway at the Women's Center",   "Feb 11 &middot; Instagram",             "861",    "77",  "19s"),
    ("As an orthopedic surgeon at Santiam Orthopedics","Apr 16 &middot; Instagram",            "398",    "43",  "17s"),
    ("A closer look inside our lab",                  "Apr 23 &middot; Instagram",             "1,107",  "38",  "13s"),
    ("Mental health is part of overall health",       "May 18 &middot; Facebook + Instagram",  "565",    "37",  "9s"),
    ("Happy Nurses Week to our incredible nurses",    "May 11 &middot; Facebook + Instagram",  "873",    "34",  "6s"),
    ("Coffee Corner update",                          "Jun 17 &middot; Facebook + Instagram",  "870",    "25",  "5s"),
]

TOP_POSTS = [
    ("Mill City, Idanha and Detroit service update",  "May 28 &middot; Facebook",             "7,376",  "135", "Graphic"),
    ("Coffee Corner hours expanded",                  "Jun 29 &middot; Facebook",             "12,566", "113", "Photo"),
    ("When seconds count, you shouldn't have to drive","Jul 29 &middot; Facebook",            "5,536",  "89",  "Photo"),
    ("Another year in the books, 37th Annual",        "Jun 10 &middot; Facebook + Instagram", "2,892",  "75",  "Graphic"),
    ("A fantastic day at the Aumsville Corn Festival","Aug 17 &middot; Instagram",            "2,851",  "54",  "Photo"),
    ("Proud to celebrate with the community",         "Jul 6 &middot; Facebook + Instagram",  "3,450",  "53",  "Photo"),
    ("Patient advocacy, and what it looks like here", "Aug 29 &middot; Facebook",             "3,006",  "48",  "Photo"),
]

CHANNELS = [
    ("Facebook",  "Santiam Hospital &amp; Clinics",      "3,868,116", "12,655", "801", "0.33%"),
    ("Instagram", "Views up 69%, followers up 54%",      "283,870",   "2,962",  "250", "1.04%"),
    ("Facebook",  "Family Birth Center",                 "149,562",   "4,875",  "300", "3.26%"),
    ("LinkedIn",  "Zero paid spend, all organic",        "28,333",    "428",    "188", "4.40%"),
]

SHARE = [("Of posts", [22.9, 6.9, 70.2]),
         ("Of reach", [38.5, 8.0, 53.5]),
         ("Of reactions", [42.1, 7.4, 50.5])]

WORKING = [
    ("Video is the strongest format you have.", "18 median organic reactions and a 2.90% engagement rate, ahead of every still creative type."),
    ("Instagram rewards the real thing.", "Photographs earn 15 median reactions there against 3 for designed graphics, at a 3.28% rate."),
    ("Instagram engagement runs well ahead of Facebook", "across every creative type, at 2.4% to 3.3%."),
    ("Facebook loves meeting the team.", "Provider introductions reach a median 1,933 people there, the widest of any still format."),
    ("Graphics earn the shares.", "On Facebook they average 3.33 shares per post, the most of anything measured."),
    ("Community news travels furthest.", "The Salem Health affiliation post reached 30,591 people with no spend behind it."),
]

NEXT = [
    ("More short video.", "Clips of 5 to 20 seconds are already the top performer, so raising the count is the clearest lift available."),
    ("Match creative to platform.", "Candid photography and video to Instagram, provider introductions and shareable graphics to Facebook."),
    ("Build a capture habit.", "A phone in hand on rounds, at new-hire welcomes and at community events turns everyday moments into the best posts."),
    ("Keep introducing the team.", "Provider spotlights travel furthest on Facebook and are an easy series to keep running."),
    ("Lean into Instagram's momentum.", "Views up 69% and followers up 54% make it the fastest-growing channel to feed."),
]

# ---------------------------------------------------------------- helpers
def creative_rows():
    out = []
    for r in CREATIVE:
        fp, fr, fk = r["fb"]
        ip, ir, ik = r["ig"]
        out.append(
            '<tr>'
            '<td><span class="cn">{name}</span><span class="cs">{desc}</span></td>'
            '<td class="grp">{fp}</td><td>{fr}</td>'
            '<td><span class="big{fw}">{fk}</span></td>'
            '<td class="grp">{ip}</td><td>{ir}</td>'
            '<td><span class="big{iw}">{ik}</span></td>'
            '<td class="grp"><span class="strength">{st}</span></td>'
            '</tr>'.format(name=r["name"], desc=r["desc"], fp=fp, fr=fr, fk=fk,
                           ip=ip, ir=ir, ik=ik, st=r["strength"],
                           fw=" win" if r["hi"] == "fb" else "",
                           iw=" win" if r["hi"] == "ig" else ""))
    v = VIDEO_ROW
    out.append(
        '<tr class="vrow">'
        '<td><span class="cn">Video <span class="rl">Reels</span></span>'
        '<span class="cs">Short clips, 5 to 20 seconds</span></td>'
        '<td class="grp">{p}</td>'
        '<td colspan="5" class="vcell">All placements combined &middot; '
        '<b>{r}</b> median reach &middot; <b class="win">{k}</b> median reactions &middot; '
        '<b>{e}</b> engagement rate</td>'
        '<td class="grp"><span class="strength">Best of any format</span></td>'
        '</tr>'.format(p=v["posts"], r=v["reach"], k=v["react"], e=v["er"]))
    return "\n".join(out)


def er_charts():
    cells = []
    for name, who, vals in ER_MONTHLY:
        mx = max(vals)
        bars = "".join(
            '<div class="mbar" style="height:{h}%" title="{m}: {v:.2f}%"></div>'.format(
                h=max(4, round(v / mx * 100)), m=MONTHS[i], v=v)
            for i, v in enumerate(vals))
        labs = "".join('<span>{}</span>'.format(m) for m in MONTHS)
        cells.append(
            '<div class="mch"><h3>{n}</h3><p class="who">{w}</p>'
            '<div class="mplot">{b}</div><div class="mmo">{l}</div>'
            '<div class="mfoot">high <b>{mx:.2f}%</b></div></div>'.format(
                n=name, w=who, b=bars, l=labs, mx=mx))
    return "\n".join(cells)


def video_rows():
    return "\n".join(
        '<tr><td><span class="pw">{t}</span><span class="pd">{d}</span></td>'
        '<td>{r}</td><td>{k}</td><td>{p}</td></tr>'.format(t=t, d=d, r=r, k=k, p=p)
        for t, d, r, k, p in TOP_VIDEOS)


def post_rows():
    return "\n".join(
        '<tr><td><span class="pw">{t}</span><span class="pd">{d}</span></td>'
        '<td>{r}</td><td>{k}</td>'
        '<td><span class="tagp {c}">{ty}</span></td></tr>'.format(
            t=t, d=d, r=r, k=k, ty=ty, c="ph" if ty == "Photo" else "gr")
        for t, d, r, k, ty in TOP_POSTS)


def channel_rows():
    return "\n".join(
        '<tr><td><span class="pw" style="font-weight:700">{n}</span>'
        '<span class="pd">{w}</span></td>'
        '<td>{v}</td><td>{i}</td><td>{f}</td><td class="rate">{e}</td></tr>'.format(
            n=n, w=w, v=v, i=i, f=f, e=e)
        for n, w, v, i, f, e in CHANNELS)


def share_rows():
    out = []
    for lab, vals in SHARE:
        segs = "".join(
            '<span class="seg s{n}" style="width:{w}%">{w:.0f}%</span>'.format(n=i + 1, w=v)
            for i, v in enumerate(vals))
        out.append('<div class="evrow"><span class="evlab">{l}</span>'
                   '<span class="evbar">{s}</span></div>'.format(l=lab, s=segs))
    return "\n".join(out)


def bullets(items, cls=""):
    return "\n".join('<li><b>{h}</b> {t}</li>'.format(h=h, t=t) for h, t in items)


# ---------------------------------------------------------------- page
HTML = """<title>Santiam Social Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans:wght@400;600;700&display=swap">

<style>
/* Santiam Hospital & Clinics one-sheet. Navy #00364E, orange #EB8923.
   Static HTML only: no page scripts, and the logo SVG carries fills as attributes. */
:root{
  --navy:#00364E; --orange:#EB8923;
  --ink:#00364E; --body:#33505A; --muted:#758C96;
  --rule:#D9E1E5; --rule-mid:#AFC1C9; --wash:#F4F7F8;
  --bar2:#9DB6BF; --bar3:#CBD8DD; --stage:#DDE4E7;
}
@media (prefers-color-scheme:dark){ :root:not([data-theme="light"]){ --stage:#0B222C; } }
:root[data-theme="dark"]{ --stage:#0B222C; }
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--stage);font-family:"Open Sans",Arial,sans-serif;
  color:var(--body);-webkit-font-smoothing:antialiased}
.stage{overflow-x:auto;padding:24px 16px 36px}
.hint{max-width:816px;margin:0 auto 12px;font-family:"Montserrat",sans-serif;font-size:11px;
  letter-spacing:.1em;text-transform:uppercase;color:var(--muted);text-align:center}
.sheet{width:816px;height:1056px;margin:0 auto;background:#FFF;color:var(--body);
  box-shadow:0 2px 6px rgba(0,0,0,.14),0 18px 50px -22px rgba(0,0,0,.5);
  display:flex;flex-direction:column;overflow:hidden}
.inner{flex:1;display:flex;flex-direction:column;padding:16px 32px 9px;gap:9px;min-height:0}

.band{background:var(--navy);padding:12px 32px 11px;display:flex;align-items:flex-end;
  justify-content:space-between;gap:20px;flex:none}
.band .logo{width:208px;flex:none}
.band .logo svg{width:100%;height:auto;display:block}
.meta{text-align:right;color:#9FBECD;font-family:"Montserrat",sans-serif;font-size:7.6px;
  font-weight:700;letter-spacing:.14em;text-transform:uppercase;line-height:1.8}
.meta strong{color:#fff;font-size:8.6px}
.hair{height:3px;background:var(--orange);flex:none}

.top{display:grid;grid-template-columns:1fr 286px;gap:18px;align-items:start}
h1{font-family:"Montserrat",sans-serif;font-weight:700;font-size:22px;line-height:1.12;
  letter-spacing:-.013em;color:var(--ink);margin:0 0 7px;text-wrap:balance}
.lede{margin:0;font-size:8.6px;line-height:1.48;color:var(--body)}
.lede b{color:var(--ink);font-weight:700}
.figs{display:grid;grid-template-columns:1fr 1fr;border-top:2px solid var(--ink);
  border-left:1px solid var(--rule)}
.fig{padding:5px 8px 6px;border-right:1px solid var(--rule);border-bottom:1px solid var(--rule)}
.fig dt{font-family:"Montserrat",sans-serif;font-size:5.9px;font-weight:700;letter-spacing:.12em;
  text-transform:uppercase;color:var(--muted);margin:0 0 2px}
.fig dd{margin:0;font-family:"Montserrat",sans-serif;font-size:18px;font-weight:700;line-height:1;
  letter-spacing:-.02em;color:var(--ink);font-variant-numeric:tabular-nums}
.fig p{margin:2px 0 0;font-size:6.2px;color:var(--muted);line-height:1.28}
.up{color:var(--orange);font-weight:700}

.h{display:flex;align-items:baseline;gap:7px;border-bottom:1px solid var(--rule-mid);
  padding-bottom:3px;margin:0 0 5px;flex:none}
.h h2{font-family:"Montserrat",sans-serif;font-weight:700;font-size:9.8px;color:var(--ink);
  margin:0;flex:none}
.h span{font-size:6.7px;color:var(--muted);line-height:1.28}

table{border-collapse:collapse;width:100%;font-size:7.9px}
thead th{background:var(--navy);color:#fff;font-family:"Montserrat",sans-serif;font-size:5.9px;
  font-weight:700;letter-spacing:.09em;text-transform:uppercase;padding:4px 6px;
  text-align:right;white-space:nowrap}
thead th:first-child{text-align:left}
thead th.grp{border-left:1px solid rgba(255,255,255,.28)}
td{padding:5px 6px;text-align:right;border-bottom:1px solid var(--rule);
  font-variant-numeric:tabular-nums;white-space:nowrap;color:var(--body)}
td:first-child{text-align:left;color:var(--ink)}
td.grp{border-left:1px solid var(--rule)}
tbody tr:last-child td{border-bottom:none}
.cn{font-family:"Montserrat",sans-serif;font-weight:700;font-size:8.1px;color:var(--ink)}
.cs{display:block;color:var(--muted);font-weight:400;font-size:6.3px;line-height:1.28;
  white-space:normal}
.rl{font-size:5.6px;letter-spacing:.08em;text-transform:uppercase;color:var(--orange);
  vertical-align:1px}
.big{font-family:"Montserrat",sans-serif;font-weight:700;font-size:10px;color:var(--ink)}
.win{color:var(--orange)}
.rate{font-weight:700;color:var(--ink)}
.strength{font-size:6.3px;color:var(--orange);font-weight:700;font-family:"Montserrat",sans-serif;
  letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}
.vrow td{background:var(--wash)}
.vcell{text-align:center;font-size:7.4px;color:var(--body);white-space:nowrap}
.vcell b{color:var(--ink);font-weight:700}

.mrow{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--rule-mid)}
.mch{padding:5px 8px 4px;border-right:1px solid var(--rule);border-bottom:1px solid var(--rule)}
.mch:last-child{border-right:none}
.mch h3{font-family:"Montserrat",sans-serif;font-size:7.1px;font-weight:700;color:var(--ink);margin:0}
.mch .who{font-size:5.9px;color:var(--muted);margin:0 0 5px}
.mplot{display:grid;grid-template-columns:repeat(8,1fr);gap:2.4px;align-items:end;height:30px;
  border-bottom:1px solid var(--rule-mid)}
.mbar{background:var(--orange);min-height:1.5px}
.mmo{display:grid;grid-template-columns:repeat(8,1fr);gap:2.4px;margin-top:2px}
.mmo span{font-size:5.4px;color:var(--muted);text-align:center}
.mfoot{margin-top:3px;font-size:5.9px;color:var(--muted);text-align:right}
.mfoot b{color:var(--orange);font-weight:700;font-variant-numeric:tabular-nums}

.mini{width:100%;font-size:7.2px}
.mini td{padding:3.6px 0;border-bottom:1px solid var(--rule);text-align:right}
.mini td:first-child{text-align:left;white-space:normal;padding-right:7px;line-height:1.26}
.mini tr:last-child td{border-bottom:none}
.mini .pw{display:block;color:var(--ink);font-size:7.2px}
.mini .pd{font-size:6.1px;color:var(--muted)}
.mini th{background:transparent;color:var(--muted);font-family:"Montserrat",sans-serif;
  font-size:5.7px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;
  padding:0 0 3px;border-bottom:1px solid var(--rule-mid);text-align:right}
.mini th:first-child{text-align:left}
.tagp{display:inline-block;font-family:"Montserrat",sans-serif;font-size:5.4px;font-weight:700;
  letter-spacing:.06em;text-transform:uppercase;padding:1px 4px;border:.8px solid currentColor}
.tagp.ph{color:var(--orange)} .tagp.gr{color:var(--muted)}

.evr{display:flex;flex-direction:column;gap:4px}
.evrow{display:grid;grid-template-columns:76px 1fr;align-items:center;gap:7px}
.evlab{font-family:"Montserrat",sans-serif;font-size:6px;font-weight:700;letter-spacing:.07em;
  text-transform:uppercase;color:var(--muted);text-align:right}
.evbar{display:flex;height:15px;overflow:hidden}
.seg{display:flex;align-items:center;justify-content:center;font-family:"Montserrat",sans-serif;
  font-size:6.6px;font-weight:700;color:#fff}
.seg.s1{background:var(--orange)} .seg.s2{background:var(--bar2)}
.seg.s3{background:var(--bar3);color:var(--ink)}
.evkey{display:flex;gap:9px;justify-content:flex-end;font-size:5.9px;color:var(--muted);margin:0 0 4px}
.evkey i{display:inline-block;width:7px;height:7px;margin-right:4px;vertical-align:-1px}

.split{display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:start}
.list{margin:0;padding:0;list-style:none;display:flex;flex-direction:column;gap:4px}
.list li{font-size:7.1px;line-height:1.36;padding-left:8px;border-left:2px solid var(--orange);
  color:var(--body)}
.list.b li{border-left-color:var(--bar2)}
.list li b{color:var(--ink);font-weight:700}

.foot{margin-top:auto;border-top:1.5px solid var(--ink);padding-top:5px;display:flex;
  justify-content:space-between;font-size:6.1px;color:var(--muted);flex:none}

@page{size:Letter portrait;margin:0}
@media print{
  body{background:#fff}
  .stage{padding:0;overflow:visible}
  .hint{display:none}
  .sheet{box-shadow:none;width:8.5in;height:11in}
  *{-webkit-print-color-adjust:exact;print-color-adjust:exact}
}
:focus-visible{outline:2px solid var(--orange);outline-offset:2px}
</style>

<p class="hint">Letter portrait &middot; prints to a single sheet</p>
<div class="stage">
<div class="sheet" id="sheet">

  <header class="band">
    <span class="logo">__LOGO__</span>
    <div class="meta">
      <div><strong>Social Highlights</strong></div>
      <div>January 1 &ndash; August 31, 2026</div>
      <div>Prepared by Duo Group</div>
    </div>
  </header>
  <div class="hair"></div>

  <div class="inner">

    <div class="top">
      <div>
        <h1>Video leads, and real photography wins on Instagram.</h1>
        <p class="lede">Santiam content was seen <b>4.33 million times</b> and earned
        <b>20,923 interactions</b>, with <b>1,539 new followers</b> joining the community.
        Looking at organic performance alone, <b>video is the strongest format</b> at 18 median
        reactions and a 2.90% engagement rate. Among still creative, <b>real photographs lead on
        Instagram</b> and <b>provider introductions lead on Facebook</b>, so the two platforms are
        worth feeding differently.</p>
      </div>
      <dl class="figs">
        <div class="fig"><dt>Views</dt><dd>4.33M</dd><p>Across all channels</p></div>
        <div class="fig"><dt>Interactions</dt><dd>20,923</dd><p>Reactions, comments, shares</p></div>
        <div class="fig"><dt>New followers</dt><dd>1,539</dd><p>Community growth</p></div>
        <div class="fig"><dt>Link clicks</dt><dd>49.3K</dd><p><span class="up">Up 128%</span> on Facebook</p></div>
      </dl>
    </div>

    <div>
      <div class="h"><h2>Creative scorecard</h2><span>Organic medians per post. Ad reach and ad reactions are removed. The two platforms reward different things.</span></div>
      <table>
        <thead><tr>
          <th scope="col">Creative type</th>
          <th scope="col" class="grp">FB posts</th><th scope="col">FB reach</th><th scope="col">FB reactions</th>
          <th scope="col" class="grp">IG posts</th><th scope="col">IG reach</th><th scope="col">IG reactions</th>
          <th scope="col" class="grp">Strength</th>
        </tr></thead>
        <tbody>
__CREATIVE__
        </tbody>
      </table>
    </div>

    <div>
      <div class="h"><h2>Engagement rate by month</h2><span>Facebook closes the period at 0.52%, its strongest month of the year. LinkedIn uses its own platform formula, which also counts clicks.</span></div>
      <div class="mrow">
__ERCHARTS__
      </div>
    </div>

    <div class="split">
      <div>
        <div class="h"><h2>Top organic videos</h2><span>18 median reactions</span></div>
        <table class="mini">
          <thead><tr><th scope="col">Video</th><th scope="col">Reach</th><th scope="col">React.</th><th scope="col">Avg play</th></tr></thead>
          <tbody>
__VIDEOS__
          </tbody>
        </table>
      </div>
      <div>
        <div class="h"><h2>Top organic posts</h2><span>Ad reach removed</span></div>
        <table class="mini">
          <thead><tr><th scope="col">Post</th><th scope="col">Reach</th><th scope="col">React.</th><th scope="col">Type</th></tr></thead>
          <tbody>
__POSTS__
          </tbody>
        </table>
      </div>
    </div>

    <div class="split">
      <div>
        <div class="h"><h2>Channel highlights</h2><span>Full period</span></div>
        <table class="mini">
          <thead><tr><th scope="col">Channel</th><th scope="col">Views</th><th scope="col">Interactions</th><th scope="col">Followers</th><th scope="col">Eng.</th></tr></thead>
          <tbody>
__CHANNELS__
          </tbody>
        </table>
      </div>
      <div>
        <div class="h"><h2>Photography punches above its weight</h2><span>Share of output against share of engagement</span></div>
        <p class="evkey">
          <span><i style="background:var(--orange)"></i>Real photograph</span>
          <span><i style="background:var(--bar2)"></i>Provider card</span>
          <span><i style="background:var(--bar3)"></i>Designed graphic</span>
        </p>
        <div class="evr">
__SHARE__
        </div>
      </div>
    </div>

    <div class="split">
      <div>
        <div class="h"><h2>What's working</h2></div>
        <ul class="list">
__WORKING__
        </ul>
      </div>
      <div>
        <div class="h"><h2>Where we grow next</h2></div>
        <ul class="list b">
__NEXT__
        </ul>
      </div>
    </div>

    <div class="foot">
      <span>Santiam Hospital &amp; Clinics &middot; Stayton, Oregon</span>
      <span>Prepared by Duo Group &middot; September 10, 2026</span>
    </div>
  </div>
</div>
</div>
"""

html = (HTML
        .replace("__LOGO__", LOGO)
        .replace("__CREATIVE__", creative_rows())
        .replace("__ERCHARTS__", er_charts())
        .replace("__VIDEOS__", video_rows())
        .replace("__POSTS__", post_rows())
        .replace("__CHANNELS__", channel_rows())
        .replace("__SHARE__", share_rows())
        .replace("__WORKING__", bullets(WORKING))
        .replace("__NEXT__", bullets(NEXT)))

non_ascii = sum(1 for c in html if ord(c) > 127)
html = html.encode('ascii', 'xmlcharrefreplace').decode('ascii')

out = ROOT / 'santiam-social-report.html'
out.write_text(html)

assert '<script' not in html, "page must contain no scripts"
assert html.count('<style>') == 1, "expected exactly one stylesheet, got %d" % html.count('<style>')
print("wrote %s  %d bytes  |  %d non-ASCII escaped  |  scripts: %d  |  svg style blocks: 0"
      % (out.name, len(html), non_ascii, html.count('<script')))
